[package]
name = "musiq-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
lofty = "0.24"
walkdir = "2"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
time = { version = "0.3", features = ["formatting"] }
rodio = "0.22"
rand = "0.10"

[dev-dependencies]
tempfile = "3"
