[package]
name = "musiq-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
musiq-db = { workspace = true }
musiq-metadata = { workspace = true }
musiq-audio-engine = { workspace = true }
musiq-net = { workspace = true }
musiq-plugins = { workspace = true }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
