[package]
name = "musiq-db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "uuid", "chrono", "migrate"] }
serde.workspace = true
tokio.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono = { version = "0.4", features = ["serde"] }
